[build]
  publish = "dist"
  functions = "netlify/functions"

[functions]
  # Increase memory allocation for better performance
  memory = 1024

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 